### PR TITLE
Fix resolve function signature for GraphQL 0.6.0.

### PR DESCRIPTION
**Pull request by AndreaOrru**
See issue #11.

Tests run just fine on my machine, not sure why they are failing on Travis...?

### CODE REVIEW

**Comment by brysgo** [comment]
I'm going to check this out today and hopefully merge it.

**Comment by brysgo** [comment]
So the tests passed for me too, until I updated to the latest version of nodejs and reinstalled my node modules. Now I get the same error as travis. If you would like to troubleshoot it @AndreaOrru I will give you first dibs, otherwise I will dig more into it.

Thanks!

**Comment by brysgo** [comment]
Just had to update jest-cli and the tests passed.

**Comment by AndreaOrru** [comment]
Thanks for this.

**Pull request merged**
